kando/cards/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "cards"

urlpatterns = [
    path("<int:card_id>/", views.card_detail, name="card_detail"),
    path("<int:card_id>/~edit/", views.edit_card, name="edit_card"),
    path("<int:card_id>/~delete/", views.delete_card, name="delete_card"),
    path("<int:project_id>/~create/", views.create_card, name="create_card"),
    path("<int:column_id>/~move/", views.move_cards, name="move_cards"),
    path(
        "<int:project_id>/<int:column_id>/~create/",
        views.create_card,
        name="create_card_for_column",
    ),
]

kando/columns/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "columns"

urlpatterns = [
    path("<int:project_id>/~create/", views.create_column, name="create_column"),
    path("<int:project_id>/~move/", views.move_columns, name="move_columns"),
    path("<int:column_id>/", views.column_detail, name="column_detail"),
    path("<int:column_id>/~edit/", views.edit_column, name="edit_column"),
    path("<int:column_id>/~delete/", views.delete_column, name="delete_column"),
]

kando/invites/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "invites"

urlpatterns = [
    path("<int:project_id>/~send/", views.send_invites, name="send_invites"),
    path("<str:invite_id>/~accept/", views.accept_invite, name="accept_invite"),
]

kando/projects/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.projects_overview, name="projects_overview"),
    path("<int:project_id>/board/", views.project_board, name="project_board"),
    path("<int:project_id>/members/", views.project_members, name="project_members"),
    path(
        "<int:member_id>/~/change-role/",
        views.change_member_role,
        name="change_member_role",
    ),
    path("<int:member_id>/~/remove/", views.remove_member, name="remove_member",),
    path(
        "<int:project_id>/member/<slug:username>/",
        views.project_member_detail,
        name="member_detail",
    ),
    path("<int:project_id>/~edit/", views.edit_project, name="edit_project"),
    path("<int:project_id>/~delete/", views.delete_project, name="delete_project"),
    path(
        "<int:project_id>/~duplicate/",
        views.duplicate_project,
        name="duplicate_project",
    ),
    path("~create/", views.create_project, name="create_project"),
]

kando/cards/models.py
# Django
from django.conf import settings
from django.db import models
from django.urls import reverse

# Third Party Libraries
from model_utils import FieldTracker
from model_utils.models import TimeStampedModel

# Kando
from kando.columns.models import Column
from kando.projects.models import Project


class CardQuerySet(models.QuerySet):
    def accessible_to(self, user):
        """Returns all projects a user is a member of,
        either owner or member"""
        return self.filter(
            models.Q(project__owner=user)
            | models.Q(
                project__projectmember__user=user,
                project__projectmember__is_active=True,
            )
        )


class CardManager(models.Manager.from_queryset(CardQuerySet)):
    ...


class Card(TimeStampedModel):

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="owned_cards",
    )

    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="assigned_cards",
    )

    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    position = models.IntegerField(default=0)
    is_active = models.BooleanField(default=0)

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    deadline = models.DateField(null=True, blank=True)

    complexity = models.PositiveIntegerField(default=1)
    priority = models.PositiveIntegerField(default=1)

    hours_estimated = models.PositiveIntegerField(default=0)
    hours_spent = models.PositiveIntegerField(default=0)

    objects = CardManager()

    tracker = FieldTracker(fields=["column"])

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cards:card_detail", args=[self.id])

    def save(self, *args, **kwargs):
        if not self.position or self.tracker.has_changed("column"):
            self.position = (
                self.column.card_set.aggregate(models.Max("position"))["position__max"]
                or 0
            ) + 1
        return super().save(*args, **kwargs)

kando/projects/models.py
# Django
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext as _

# Third Party Libraries
from model_utils.models import TimeStampedModel


class ProjectQuerySet(models.QuerySet):
    def accessible_to(self, user):
        """Returns all projects a user is a member of,
        either owner or member"""
        return self.filter(
            models.Q(owner=user)
            | models.Q(projectmember__user=user, projectmember__is_active=True)
        )


class ProjectManager(models.Manager.from_queryset(ProjectQuerySet)):
    def create_project(self, name, owner, **kwargs):
        """Creates a new project with default columns """

        project = self.create(name=name, owner=owner, **kwargs)

        for position, name in enumerate(
            (_("Backlog"), _("Ready"), ("In Progress"), _("Done")), 1
        ):
            project.column_set.create(name=name, position=position)

        return project


class Project(TimeStampedModel):

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="owned_projects",
    )

    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through="ProjectMember",
        blank=True,
        related_name="projects",
    )

    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    is_active = models.BooleanField(default=True)

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    objects = ProjectManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("projects:project_board", args=[self.id])


class ProjectMember(TimeStampedModel):
    class Role(models.TextChoices):
        # add tasks, edit/move own tasks, assign myself to tasks
        MEMBER = "member", _("Member")
        # edit others' tasks, assign tasks
        MANAGER = "manager", _("Manager")
        # add users to project, change columns, change permissions, edit project, delete project
        # owner has all these permissions by default
        ADMIN = "admin", _("Admin")

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    role = models.CharField(
        choices=Role.choices, max_length=12, default=Role.MEMBER, db_index=True
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                name="unique_project_member", fields=["project", "user"]
            )
        ]

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse(
            "projects:member_detail", args=[self.project.id, self.user.username]
        )

kando/cards/forms.py
# Django
from django import forms

# Local
from .models import Card


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = (
            "name",
            "assignee",
            "description",
            "complexity",
            "priority",
            "hours_estimated",
            "column",
        )

    def __init__(self, *args, **kwargs):
        project = kwargs.pop("project", None)
        super().__init__(*args, **kwargs)
        project = project or self.instance.project
        if project is None:
            raise ValueError(
                "Project must be provided as argument or with card instance"
            )
        self.project = project

        self.fields["column"].queryset = self.project.column_set.order_by("position")

        users_qs = self.project.members.order_by("name", "username")

        if users_qs.count() == 0:
            del self.fields["assignee"]
        else:
            self.fields["assignee"].queryset = users_qs

kando/projects/forms.py
# Django
from django import forms
from django.utils.translation import gettext_lazy as _

# Local
from .models import Project, ProjectMember


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = (
            "name",
            "description",
        )
        labels = {"name": _("Project Name")}


class ProjectCreationForm(ProjectForm):
    def save(self, owner):
        return Project.objects.create_project(owner=owner, **self.cleaned_data)


class ProjectMemberRoleForm(forms.ModelForm):
    class Meta:
        model = ProjectMember
        fields = ("role",)
        widgets = {"role": forms.RadioSelect}

kando/cards/views.py
# Django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST

# Kando
from kando.columns.models import Column
from kando.common.dragdrop import sort_draggable_items
from kando.common.http import HttpResponseNoContent
from kando.projects.models import Project
from kando.users.utils import has_perm_or_403

# Local
from .forms import CardForm
from .models import Card


@login_required
def create_card(request, project_id, column_id=None):
    project = get_object_or_404(Project.objects.select_related("owner"), pk=project_id)
    has_perm_or_403(request.user, "cards.create_card", project)

    if column_id:
        column = get_object_or_404(project.column_set.all(), pk=column_id)
    else:
        column = None

    if request.method == "POST":
        form = CardForm(request.POST, project=project)
        if form.is_valid():
            card = form.save(commit=False)
            card.owner = request.user
            card.project = project
            card.save()
            messages.success(request, _("Your card has been added"))
            return redirect(card)
    else:
        form = CardForm(initial={"column": column}, project=project)

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (project.name, project.get_absolute_url()),
    ]
    if column:
        breadcrumbs += [(column.name, column.get_absolute_url())]
    breadcrumbs += [(_("New Card"), None)]

    return TemplateResponse(
        request,
        "cards/card_form.html",
        {
            "form": form,
            "project": project,
            "column": column,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
def card_detail(request, card_id):
    card = get_object_or_404(
        Card.objects.select_related(
            "project", "column", "project__owner", "assignee", "owner"
        ),
        pk=card_id,
    )
    has_perm_or_403(request.user, "cards.view_card", card)

    tasks = card.task_set.select_related(
        "card", "owner", "card__owner", "card__assignee"
    ).order_by("position")

    attachments = card.attachment_set.select_related(
        "card", "owner", "card__owner", "card__assignee"
    ).order_by("created")

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (card.project.name, card.project.get_absolute_url()),
        (card.name, None),
    ]

    return TemplateResponse(
        request,
        "cards/detail.html",
        {
            "card": card,
            "tasks": tasks,
            "attachments": attachments,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
def edit_card(request, card_id):
    card = get_object_or_404(
        Card.objects.select_related("project", "column", "project__owner", "owner"),
        pk=card_id,
    )
    has_perm_or_403(request.user, "cards.change_card", card)
    if request.method == "POST":
        form = CardForm(request.POST, instance=card)
        if form.is_valid():
            form.save()
            messages.success(request, _("Card has been updated"))
            return redirect(card)
    else:
        form = CardForm(instance=card)

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (card.project.name, card.project.get_absolute_url()),
        (card.name, card.get_absolute_url()),
        (_("Edit Card"), None),
    ]

    return TemplateResponse(
        request,
        "cards/card_form.html",
        {
            "card": card,
            "form": form,
            "project": card.project,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
@require_POST
def delete_card(request, card_id):
    card = get_object_or_404(
        Card.objects.select_related("project", "project__owner"), pk=card_id,
    )
    has_perm_or_403(request.user, "cards.delete_card", card)
    card.delete()
    messages.info(request, _("Card has been deleted"))
    return redirect(card.project)


@login_required
@require_POST
def move_cards(request, column_id):
    column = get_object_or_404(
        Column.objects.select_related("project", "project__owner"), pk=column_id
    )
    qs = column.project.card_set.select_related(
        "project", "project__owner", "assignee", "owner"
    )

    for position, card in sort_draggable_items(request, qs, ["position", "column"]):
        has_perm_or_403(request.user, "cards.move_card", card)
        card.position = position
        card.column = column

    return HttpResponseNoContent()

templates/projects/_card.html
{% load i18n rules %}
{% has_perm "cards.move_card" user card as can_move_card %}
<div class="p-2 mb-3 border rounded bg-blue-500 text-white{% if can_move_card %} draggable{% endif %}"
     {% spaceless %}
     {% if can_move_card %}
     data-id="{{ card.id }}"
     data-group="shared-tasks"
     data-target="drag.draggable"
     {% endif %}{% endspaceless %}>
  <div class="mb-1">
    <a href="{{ card.get_absolute_url }}"
       class="underline font-bold">{{ card.name }}</a>
  </div>
  <div>
    <span class="font-semibold"
          title="{% translate 'Priority' %}">P {{ card.priority }}</span> /
    <span class="font-semibold"
          title="{% translate 'Complexity' %}">C {{ card.complexity }}</span> /
    <span class="font-semibold"
          title="{% translate 'Estimated Hours' %}">H {{ card.hours_estimated }}</span>
  </div>
</div>

templates/projects/board.html
{% extends "base.html" %}
{% load i18n rules %}

{% block content %}

{% has_perm "projects.change_project" user project as can_change_project %}
{% has_perm "projects.delete_project" user project as can_delete_project %}
{% has_perm "columns.create_column" user project as can_create_column %}
{% has_perm "columns.move_columns" user project as can_move_columns %}
{% has_perm "cards.create_card" user project as can_create_card %}

{% include "_breadcrumbs.html" %}

<div class="flex items-center mb-3">
  <div class="relative"
       data-controller="toggle">
    <button class="px-2 py-1 rounded border hover:bg-gray focus:outline-none text-lg mr-3"
            title="Actions..."
            data-action="toggle#toggle">
      <i class="fa fa-bars"></i>
    </button>
    <div class="rounded absolute hidden border shadow-xl z-50 opacity-100 p-2 mt-1 w-64 bg-white left-0"
         data-toggle-target="item"
         data-action="click@window->toggle#close keydown@window->toggle#close">

      {% if can_create_card %}
      <a href="{% url 'cards:create_card' project.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-plus mr-2"></i>{% translate "Add Card" %}
      </a>
      {% endif %}

      {% if can_create_column %}
      <a href="{% url 'columns:create_column' project.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-plus mr-2"></i>{% translate "Add Column" %}
      </a>
      {% endif %}

      {% if can_change_project %}
      <a href="{% url 'projects:edit_project' project.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-pen mr-2"></i>{% translate "Edit Project" %}
      </a>
      {% endif %}

      <a href="{% url 'projects:project_members' project.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-users mr-2"></i>{% translate "Users and Permissions" %}
      </a>

      <button data-controller="ajax"
              data-ajax-url-value="{% url 'projects:duplicate_project' project.id %}"
              data-action="toggle#toggle ajax#post"
              class="block p-1 rounded hover:bg-gray-100 w-full text-left">
        <i class="fa fa-copy mr-2"></i>{% translate "Duplicate Project" %}
      </button>

      {% if can_delete_project %}
      <button data-controller="ajax"
              data-ajax-confirm-value="{% translate 'Are you sure you want to delete this project?' %}"
              data-ajax-url-value="{% url 'projects:delete_project' project.id %}"
              data-action="toggle#toggle ajax#post"
              class="block p-1 rounded hover:bg-red-100 text-red-800 w-full text-left">
        <i class="fa fa-trash mr-2"></i>{% translate "Delete Project" %}
      </button>
      {% endif %}

    </div>
  </div>
  <h1 class="text-xl font-bold">{{ project.name }}</h1>

</div>

<div class="lg:flex lg:overflow-x-auto lg:whitespace-no-wrap "
     {% spaceless %}
     {% if can_move_columns %}
     data-controller="drag"
     data-drag-group-value="shared-columns"
     data-drag-url-value="{% url 'columns:move_columns' project.id %}"
     {% endif %}{% endspaceless %}>
  {% for column in columns %}
  <div class="mb-1 lg:mb-0 lg:mr-1 border{% if can_move_columns %} draggable{% endif %}"
       {% spaceless %}
       {% if can_move_columns %}
       data-toggle-target="draggable"
       data-group="shared-columns"
       data-id="{{ column.id }}"
       {% endif %}{% endspaceless %}>
    <div class="bg-gray-100 flex justify-center font-bold text-lg lg:w-64 p-2">
      <a href="{{ column.get_absolute_url }}"
         class="text-blue-800 hover:text-blue-600 underline">
        {{ column.name }}
      </a>
    </div>
    <div class="p-2 bg-white"
         data-controller="drag"
         data-drag-group-value="shared-tasks"
         data-drag-url-value="{% url 'cards:move_cards' column.id %}">
      {% for card in cards %}
      {% if card.column == column %}
      {% include "projects/_card.html" %}
      {% endif %}
      {% endfor %}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

templates/projects/member_detail.html
{% extends "base.html" %}
{% load i18n account rules widget_tweaks %}

{% block content %}
{% include "_breadcrumbs.html" %}

<h1 class="text-xl font-bold mb-3">{% user_display user_obj %}</h1>

{% if member %}

{% has_perm "projects.change_member_role" user member as can_change_member_role %}
{% has_perm "projects.remove_member" user member as can_remove_member %}

<div class="flex items-center mb-3"
     data-controller="toggle">
  <h2 class="text-lg font-semibold mr-4"
      data-toggle-target="item">{{ member.get_role_display }}</h2>
  {% if can_change_member_role %}
  <button class="rounded px-2 py-1 border hover:bg-gray-100 mr-4"
          data-action="toggle#toggle"
          data-toggle-target="item">
    <i class="fa fa-pen mr-2"></i>
    {% translate "Edit" %}
  </button>
  {% if can_remove_member %}
   <button class="rounded px-2 py-1 border hover:bg-red-100 border-red-800 text-red-800"
          data-controller="ajax"
          data-action="ajax#post"
          data-toggle-target="item"
          data-ajax-confirm-value="{% translate 'Are you sure you want to remove this member from the project?' %}"
          data-ajax-url-value="{% url 'projects:remove_member' member.id %}">
    <i class="fa fa-times mr-2"></i>
    {% translate "Remove" %}
  </button>
  {% endif %}
  <div class="hidden"
       data-toggle-target="item">
    <form data-controller="form"
          data-action="form#submit"
          method="post"
          action="{% url 'projects:change_member_role' member.id %}">
      {% render_field member_role_form.role class="" %}
      <div class="flex items-center">
        <button class="text-blue-800 hover:text-blue-600 mr-4"
                data-action="form#reset toggle#toggle">
          {% translate "Cancel" %}
          <button type="submit"
                  class="text-white bg-blue-800 hover:bg-blue-600 px-2 py-1 rounded">
            {% translate "Save" %}
          </button>
        </button>
      </div>
    </form>
  </div>
  {% endif %}
</div>
{% else %}
<h2 class="text-lg font-semibold mb-3">{% translate "Project Owner" %}</h2>
{% endif %}



{% if owned_cards %}
<h2 class="text-lg font-semibold mb-3">{% translate "Owned Cards" %}</h2>
<table class="table-auto p-3 w-full border mb-3">
  <thead>
    <tr class="bg-gray-100 text-left">
      <th class="p-2">{% translate "Card" %}</th>
      <th class="p-2">{% translate "Assignee" %}</th>
      <th class="p-2">{% translate "Column" %}</th>
      <th class="p-2">{% translate "Priority" %}</th>
      <th class="p-2">{% translate "Complexity" %}</th>
      <th class="p-2">{% translate "Estimated Hours" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for card in owned_cards %}
    <tr class="hover:bg-gray-100">
      <td class="p-2">
        <a href="{{ card.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600 underline">{{ card.name }}</a>
      </td>
      <td class="p-2">
        {% if card.assignee %}
        <a href="{% url 'projects:member_detail' project.id card.assignee.username %}"
           class="text-blue-800 hover:text-blue-600">
          {% user_display card.assignee %}
        </a>
        {% else %}
        {% translate "Unassigned" %}
        {% endif %}
      </td>
      <td class="p-2">
        <a href="{{ card.column.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600">
          {{ card.column.name }}
        </a>
      </td>
      <td class="p-2">{{ card.priority }}</td>
      <td class="p-2">{{ card.complexity }}</td>
      <td class="p-2">{{ card.hours_estimated }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% if assigned_cards %}
<h2 class="text-lg font-semibold mb-3">{% translate "Assigned Cards" %}</h2>
<table class="table-auto p-3 w-full border mb-3">
  <thead>
    <tr class="bg-gray-100 text-left">
      <th class="p-2">{% translate "Card" %}</th>
      <th class="p-2">{% translate "Owner" %}</th>
      <th class="p-2">{% translate "Column" %}</th>
      <th class="p-2">{% translate "Priority" %}</th>
      <th class="p-2">{% translate "Complexity" %}</th>
      <th class="p-2">{% translate "Estimated Hours" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for card in assigned_cards %}
    <tr class="{% if not forloop.last %} border-b{% endif %}">
      <td class="p-2">
        <a href="{{ card.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600 underline">{{ card.name }}</a>
      </td>
      <td class="p-2">
        <a href="{% url 'projects:member_detail' project.id card.owner.username %}"
           class="text-blue-800 hover:text-blue-600">
          {% user_display card.owner %}
        </a>
      </td>
      <td class="p-2">
        <a href="{{ card.column.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600">
          {{ card.column.name }}
        </a>
      </td>
      <td class="p-2">{{ card.priority }}</td>
      <td class="p-2">{{ card.complexity }}</td>
      <td class="p-2">{{ card.hours_estimated }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}


{% endblock content %}

templates/projects/members.html
{% extends "base.html" %}
{% load i18n account rules pagination %}

{% block content %}
{% include "_breadcrumbs.html" %}

<div class="flex items-center justify-between mb-3">
  <h1 class="text-xl font-bold">{% translate "Users and Permissions" %}</h1>
  {% has_perm "projects.add_members" user project as can_add_members %}
  {% if can_add_members %}
  <a href="{% url 'invites:send_invites' project.id %}"
     class="px-4 py-1 rounded border hover:bg-gray-100">
    <i class="fa fa-envelope mr-2"></i>
    {% translate "Invite New Users" %}
  </a>
  {% endif %}
</div>

{% paginate members as page_obj %}
<table class="table-auto border p-3 w-full bg-white rounded">
  <thead>
    <tr class="bg-gray-100 text-left">
      <th class="p-2">{% translate "User" %}</th>
      <th class="p-2">{% translate "Role" %}</th>
    </tr>
  </thead>
  <tbody>
    {% if project.owner and page_obj.number == 1 %}
    <tr class="hover:bg-gray-100">
      <td class="p-2">
        <a href="{% url 'projects:member_detail' project.id project.owner.username %}"
           class="text-blue-800 hover:text-blue-600">
          {% user_display project.owner %}
        </a>
      </td>
      <td class="p-2 font-semibold">
        {% translate "Owner" %}
      </td>
    </tr>
    {% endif %}
    {% for member in page_obj %}
    <tr class="hover:bg-gray-100">
      <td class="p-2">
        <a href="{{ member.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600">
          {% user_display member.user %}
        </a>
      </td>
      <td class="p-2">
        {{ member.get_role_display }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

templates/projects/overview.html
{% extends "base.html" %}
{% load i18n account pagination %}

{% block content %}

<div class="sm:flex items-center justify-between mb-3">
  <h1 class="text-xl font-bold mb-3 sm:mb-0">{% translate "Projects Overview" %}</h1>
  <a href="{% url 'projects:create_project' %}"
     class="px-4 py-1 rounded border bg-white hover:bg-gray-100">
    <i class="fa fa-plus mr-2"></i>{% translate "New Project" %}
  </a>
</div>

{% paginate projects as page_obj %}
<table class="table-auto border p-3 w-full bg-white rounded">
  {% if projects %}
  <thead>
    <tr class="bg-gray-100 text-left">
      <th class="p-2">{% translate "Project" %}</th>
      <th class="p-2">{% translate "Owner" %}</th>
    </tr>
  </thead>
  {% endif %}
  <tbody>
    {% for project in page_obj %}
    <tr class="{% if not forloop.last %} border-b{% endif %}">
      <td class="p-2">
        <a href="{{ project.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600">{{ project.name }}</a>
      </td>
      <td class="p-2">
        {% user_display project.owner %}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="2"
          class="flex justify-center w-full p-2">{% translate "You don't have any projects yet" %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include "_pagination.html" %}
{% endblock content %}

templates/projects/project_form.html
{% extends "base.html" %}
{% load i18n widget_tweaks %}

{% block content %}

{% include "_breadcrumbs.html" %}

<h1 class="text-xl font-bold mb-3">
  {% if project %}
  {% translate "Edit Project" %}
  {% else %}
  {% translate "New Project" %}
  {% endif %}
</h1>
<form class="p-3 bg-white border rounded w-full lg:w-2/3{% if form.errors %} border-red-800{% endif %}"
      data-controller="form"
      data-action="form#submit"
      method="post"
      action="{{ request.path }}"
      novalidate>
  {% csrf_token %}
  {% with WIDGET_ERROR_CLASS="border-red-800 text-red-800" %}
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.name.label }}
      {% render_field form.name class="p-1 w-full lg:w-96 lg:ml-3" %}
    </label>
    {% include "_form_errors.html" with errors=form.name.errors %}
    {% include "_form_help_text.html" with help_text=form.name.help_text %}
  </div>
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.description.label }}
      {% render_field form.description class="p-1 w-full"  %}
    </label>
    {% include "_form_errors.html" with errors=form.description.errors %}
    {% include "_form_help_text.html" with help_text=form.description.help_text %}
  </div>
  {% endwith %}
  <div class="flex items-center justify-end">
    {% if project %}
    <a href="{{ project.get_absolute_url }}"
       class="text-blue-800 hover:text-blue-600 mr-4">{% translate "Cancel" %}</a>
    {% endif %}
    <button type="submit"
            class="px-4 py-2 rounded bg-blue-800 hover:bg-blue-600 text-white">
      {% if project %}
      {% translate "Save Project" %}
      {% else %}
      {% translate "Create Project" %}
      {% endif %}
    </button>
  </div>
</form>
{% endblock %}