kando/attachments/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "attachments"

urlpatterns = [
    path("<int:card_id>/~/create/", views.create_attachment, name="create_attachment"),
    path(
        "<int:attachment_id>/~/delete/",
        views.delete_attachment,
        name="delete_attachment",
    ),
]

kando/cards/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "cards"

urlpatterns = [
    path("<int:card_id>/", views.card_detail, name="card_detail"),
    path("<int:card_id>/~edit/", views.edit_card, name="edit_card"),
    path("<int:card_id>/~delete/", views.delete_card, name="delete_card"),
    path("<int:project_id>/~create/", views.create_card, name="create_card"),
    path("<int:column_id>/~move/", views.move_cards, name="move_cards"),
    path(
        "<int:project_id>/<int:column_id>/~create/",
        views.create_card,
        name="create_card_for_column",
    ),
]

kando/projects/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.projects_overview, name="projects_overview"),
    path("<int:project_id>/board/", views.project_board, name="project_board"),
    path("<int:project_id>/members/", views.project_members, name="project_members"),
    path(
        "<int:member_id>/~/change-role/",
        views.change_member_role,
        name="change_member_role",
    ),
    path("<int:member_id>/~/remove/", views.remove_member, name="remove_member",),
    path(
        "<int:project_id>/member/<slug:username>/",
        views.project_member_detail,
        name="member_detail",
    ),
    path("<int:project_id>/~edit/", views.edit_project, name="edit_project"),
    path("<int:project_id>/~delete/", views.delete_project, name="delete_project"),
    path(
        "<int:project_id>/~duplicate/",
        views.duplicate_project,
        name="duplicate_project",
    ),
    path("~create/", views.create_project, name="create_project"),
]

kando/tasks/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "tasks"

urlpatterns = [
    path("<int:card_id>/~/create/", views.create_task, name="create_task"),
    path("<int:card_id>/~/move/", views.move_tasks, name="move_tasks"),
    path("<int:task_id>/~/edit/", views.edit_task, name="edit_task"),
    path("<int:task_id>/~/delete/", views.delete_task, name="delete_task"),
    path(
        "<int:task_id>/~/toggle-complete/",
        views.toggle_task_complete,
        name="toggle_complete",
    ),
]

kando/cards/models.py
# Django
from django.conf import settings
from django.db import models
from django.urls import reverse

# Third Party Libraries
from model_utils import FieldTracker
from model_utils.models import TimeStampedModel

# Kando
from kando.columns.models import Column
from kando.projects.models import Project


class CardQuerySet(models.QuerySet):
    def accessible_to(self, user):
        """Returns all projects a user is a member of,
        either owner or member"""
        return self.filter(
            models.Q(project__owner=user)
            | models.Q(
                project__projectmember__user=user,
                project__projectmember__is_active=True,
            )
        )


class CardManager(models.Manager.from_queryset(CardQuerySet)):
    ...


class Card(TimeStampedModel):

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    column = models.ForeignKey(Column, on_delete=models.CASCADE)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="owned_cards",
    )

    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="assigned_cards",
    )

    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    position = models.IntegerField(default=0)
    is_active = models.BooleanField(default=0)

    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    deadline = models.DateField(null=True, blank=True)

    complexity = models.PositiveIntegerField(default=1)
    priority = models.PositiveIntegerField(default=1)

    hours_estimated = models.PositiveIntegerField(default=0)
    hours_spent = models.PositiveIntegerField(default=0)

    objects = CardManager()

    tracker = FieldTracker(fields=["column"])

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cards:card_detail", args=[self.id])

    def save(self, *args, **kwargs):
        if not self.position or self.tracker.has_changed("column"):
            self.position = (
                self.column.card_set.aggregate(models.Max("position"))["position__max"]
                or 0
            ) + 1
        return super().save(*args, **kwargs)

kando/cards/forms.py
# Django
from django import forms

# Local
from .models import Card


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = (
            "name",
            "assignee",
            "description",
            "complexity",
            "priority",
            "hours_estimated",
            "column",
        )

    def __init__(self, *args, **kwargs):
        project = kwargs.pop("project", None)
        super().__init__(*args, **kwargs)
        project = project or self.instance.project
        if project is None:
            raise ValueError(
                "Project must be provided as argument or with card instance"
            )
        self.project = project

        self.fields["column"].queryset = self.project.column_set.order_by("position")

        users_qs = self.project.members.order_by("name", "username")

        if users_qs.count() == 0:
            del self.fields["assignee"]
        else:
            self.fields["assignee"].queryset = users_qs

kando/cards/views.py
# Django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST

# Kando
from kando.columns.models import Column
from kando.common.dragdrop import sort_draggable_items
from kando.common.http import HttpResponseNoContent
from kando.projects.models import Project
from kando.users.utils import has_perm_or_403

# Local
from .forms import CardForm
from .models import Card


@login_required
def create_card(request, project_id, column_id=None):
    project = get_object_or_404(Project.objects.select_related("owner"), pk=project_id)
    has_perm_or_403(request.user, "cards.create_card", project)

    if column_id:
        column = get_object_or_404(project.column_set.all(), pk=column_id)
    else:
        column = None

    if request.method == "POST":
        form = CardForm(request.POST, project=project)
        if form.is_valid():
            card = form.save(commit=False)
            card.owner = request.user
            card.project = project
            card.save()
            messages.success(request, _("Your card has been added"))
            return redirect(card)
    else:
        form = CardForm(initial={"column": column}, project=project)

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (project.name, project.get_absolute_url()),
    ]
    if column:
        breadcrumbs += [(column.name, column.get_absolute_url())]
    breadcrumbs += [(_("New Card"), None)]

    return TemplateResponse(
        request,
        "cards/card_form.html",
        {
            "form": form,
            "project": project,
            "column": column,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
def card_detail(request, card_id):
    card = get_object_or_404(
        Card.objects.select_related(
            "project", "column", "project__owner", "assignee", "owner"
        ),
        pk=card_id,
    )
    has_perm_or_403(request.user, "cards.view_card", card)

    tasks = card.task_set.select_related(
        "card", "owner", "card__owner", "card__assignee"
    ).order_by("position")

    attachments = card.attachment_set.select_related(
        "card", "owner", "card__owner", "card__assignee"
    ).order_by("created")

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (card.project.name, card.project.get_absolute_url()),
        (card.name, None),
    ]

    return TemplateResponse(
        request,
        "cards/detail.html",
        {
            "card": card,
            "tasks": tasks,
            "attachments": attachments,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
def edit_card(request, card_id):
    card = get_object_or_404(
        Card.objects.select_related("project", "column", "project__owner", "owner"),
        pk=card_id,
    )
    has_perm_or_403(request.user, "cards.change_card", card)
    if request.method == "POST":
        form = CardForm(request.POST, instance=card)
        if form.is_valid():
            form.save()
            messages.success(request, _("Card has been updated"))
            return redirect(card)
    else:
        form = CardForm(instance=card)

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (card.project.name, card.project.get_absolute_url()),
        (card.name, card.get_absolute_url()),
        (_("Edit Card"), None),
    ]

    return TemplateResponse(
        request,
        "cards/card_form.html",
        {
            "card": card,
            "form": form,
            "project": card.project,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
@require_POST
def delete_card(request, card_id):
    card = get_object_or_404(
        Card.objects.select_related("project", "project__owner"), pk=card_id,
    )
    has_perm_or_403(request.user, "cards.delete_card", card)
    card.delete()
    messages.info(request, _("Card has been deleted"))
    return redirect(card.project)


@login_required
@require_POST
def move_cards(request, column_id):
    column = get_object_or_404(
        Column.objects.select_related("project", "project__owner"), pk=column_id
    )
    qs = column.project.card_set.select_related(
        "project", "project__owner", "assignee", "owner"
    )

    for position, card in sort_draggable_items(request, qs, ["position", "column"]):
        has_perm_or_403(request.user, "cards.move_card", card)
        card.position = position
        card.column = column

    return HttpResponseNoContent()

templates/cards/_task_description.html
      <input type="checkbox"
             {% spaceless %}
             {% if task.completed %}
             checked{% endif %}
             class="mr-4"
             {% if can_change_task %}
             data-action="click->ajax#post:once"
             {% else %}
             disabled
             {% endif %}
             {% endspaceless %}>
      <span{% if task.completed %} class="line-through"
                                   {% endif %}>
        {{ task.description }}
        </span>

templates/cards/card_form.html
{% extends "base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
{% include "_breadcrumbs.html" %}
<h1 class="text-xl font-bold mb-3">
  {% if card %}
  {% translate "Edit Card" %}
  {% else %}
  {% translate "New Card" %}
  {% endif %}
</h1>
<form class="p-2 lg:p-3 bg-white border rounded w-full lg:w-2/3{% if form.errors %} border-red-800{% endif %}"
      data-controller="form"
      data-action="form#submit"
      method="post"
      action="{{ request.path }}"
      novalidate>
  {% csrf_token %}
  {% with WIDGET_ERROR_CLASS="border-red-800 text-red-800" %}
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.name.label }}
      {% render_field form.name class="p-1 w-full lg:w-96 lg:ml-3" %}
    </label>
    {% include "_form_errors.html" with errors=form.name.errors %}
  </div>
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.column.label }}
      {% render_field form.column class="p-1 lg:ml-3 w-full lg:w-64" %}
    </label>
    {% include "_form_errors.html" with errors=form.column.errors %}
  </div>
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.assignee.label }}
      {% render_field form.assignee class="p-1 lg:ml-3 w-full lg:w-64" %}
    </label>
    {% include "_form_errors.html" with errors=form.assignee.errors %}
  </div>
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.description.label }}
      {% render_field form.description class="p-1 w-full" %}
    </label>
    {% include "_form_errors.html" with errors=form.description.errors %}
  </div>
  <div class="mb-3 md:flex">
    <div class="mb-3 md:mr-2 md:mb-0">
      <label class="font-semibold">
        {{ form.complexity.label }}
        {% render_field form.complexity class="p-1 w-full lg:w-32 lg:ml-1" %}
      </label>
      {% include "_form_errors.html" with errors=form.complexity.errors %}
    </div>
    <div class="mb-3 md:mr-2 md:mb-0">
      <label class="font-semibold">
        {{ form.priority.label }}
        {% render_field form.priority class="p-1 w-full lg:w-32 lg:ml-1" %}
      </label>
      {% include "_form_errors.html" with errors=form.priority.errors %}
    </div>
    <div>
      <label class="font-semibold">
        {{ form.hours_estimated.label }}
        {% render_field form.hours_estimated class="p-1 w-full lg:w-32 lg:ml-1" %}
      </label>
      {% include "_form_errors.html" with errors=form.hours_estimated.errors %}
    </div>
  </div>
  {% endwith %}
  <div class="flex justify-end items-center">
    <a href="{% if card %}{{ card.get_absolute_url }}{% elif column %}{{ column.get_absolute_url }}{% else %}{{ project.get_absolute_url }}{% endif %}"
       class="text-blue-800 hover:text-blue-600 mr-4">{% translate "Cancel" %}</a>
    <button type="submit"
            class="px-4 py-2 rounded bg-blue-800 hover:bg-blue-600 text-white">
      {% if card %}
      {% translate "Save Card" %}
      {% else %}
      {% translate "Create Card" %}
      {% endif %}
    </button>
  </div>
</form>
{% endblock %}

templates/cards/detail.html
{% extends "base.html" %}
{% load i18n account rules %}

{% block content %}

{% include "_breadcrumbs.html" %}

{% has_perm "cards.create_card" user card.project as can_create_card %}
{% has_perm "cards.change_card" user card as can_change_card %}
{% has_perm "cards.delete_card" user card as can_delete_card %}

<div class="flex items-center mb-3">
  {% if can_create_card or can_change_card or can_delete_card %}
  <div class="relative"
       data-controller="toggle">
    <button class="px-2 py-1 rounded border hover:bg-gray focus:outline-none text-lg mr-3"
            title="Actions..."
            data-action="toggle#toggle">
      <i class="fa fa-bars"></i>
    </button>
    <div class="rounded absolute hidden border shadow-xl z-50 opacity-100 p-2 mt-1 w-64 bg-white left-0"
         data-toggle-target="item"
         data-action="click@window->toggle#close keydown@window->toggle#close">

      {% if can_create_card %}
      <a href="{% url 'cards:create_card_for_column' card.project.id card.column.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-plus mr-2"></i>{% translate "Add Another Card" %}
      </a>
      {% endif %}

      {% if can_change_card %}
      <a href="{% url 'cards:edit_card' card.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-pen mr-2"></i>{% translate "Edit Card" %}
      </a>
      {% endif %}

      {% if can_delete_card %}
      <button data-controller="ajax"
              data-ajax-confirm-value="{% translate 'Are you sure you want to delete this card?' %}"
              data-ajax-url-value="{% url 'cards:delete_card' card.id %}"
              data-action="toggle#toggle ajax#post"
              class="block p-1 rounded hover:bg-red-100 text-red-800 w-full text-left">
        <i class="fa fa-trash mr-2"></i>{% translate "Delete Card" %}
      </button>
      {% endif %}

    </div>
  </div>
  {% endif %}

  <h1 class="text-xl font-bold">{{ card.name }}</h1>
</div>

<div class="flex items-center mb-3">
  <div class="mr-2 font-bold">{% translate "Owner" %}</div>
  <div class="mr-4">
    <a href="{% url 'projects:member_detail' card.project.id card.owner.username %}"
       class="text-blue-800 hover:text-blue-600">
      {% user_display card.owner %}
    </a>
  </div>
  <div class="mr-2 font-bold">{% translate "Assignee" %}</div>
  <div class="">
    {% if card.assignee %}
    <a href="{% url 'projects:member_detail' card.project.id card.assignee.username %}"
       class="text-blue-800 hover:text-blue-600">
      {% user_display card.assignee %}
    </a>
    {% else %}
    {% translate "Unassigned" %}
    {% endif %}
  </div>
</div>

<div class="flex items-center mb-3">
  <div class="mr-2 font-bold">{% translate "Priority" %}</div>
  <div class="mr-2">{{ card.priority }}</div>
  <div class="mr-2 font-bold">{% translate "Complexity" %}</div>
  <div class="mr-2">{{ card.complexity }}</div>
  <div class="mr-2 font-bold">{% translate "Estimated Hours" %}</div>
  <div class="">{{ card.hours_estimated }}</div>
</div>

{% if card.description %}
<p class="mb-3 markdown">
  {{ card.description|linebreaksbr|urlize }}
</p>
{% endif %}

<h2 class="text-lg font-semibold mb-3">{% translate "Tasks" %}</h2>
{% if not tasks %}
<p class="mb-3 italic">
  {% translate "This card does not have any tasks" %}
</p>
{% endif %}

{% has_perm "tasks.move_tasks" user card as can_move_tasks %}
<div {% spaceless %}{% if can_move_tasks %}data-controller="drag"
     data-drag-group-value="shared"
     data-drag-url-value="{% url 'tasks:move_tasks' card.id %}"
     {% endif %}{% endspaceless %}>
  {% for task in tasks %}

  <div data-controller="toggle"
       class="draggable">

    <div data-toggle-target="item"
         class="mb-3 hidden">
      <form class="sm:flex border p-2 items-center justify-between"
            data-controller="form"
            data-action="form#submit"
            method="post"
            action="{% url 'tasks:edit_task' task.id %}">

        <div>
          <input type="text"
                 required
                 name="description"
                 value="{{ task.description }}"
                 class="p-1 w-96">
        </div>
        <div>
          <button type="button"
                  data-action="toggle#toggle"
                  class="text-blue-800 hover:text-blue-600 mr-2">
            {% translate "Cancel" %}
          </button>
          <button type="submit"
                  class="px-4 py-1 rounded bg-blue-800 hover:bg-blue-100 text-white">
            {% translate "Save" %}
          </button>
        </div>
      </form>
    </div>

    <div data-toggle-target="item"
         class="mb-3">
      <div class="sm:flex border p-2 items-center justify-between"
           data-id="{{ task.id }}"
           data-group="shared"
           data-drag-target="draggable">
        {% has_perm "tasks.change_task" user task as can_change_task %}
        {% has_perm "tasks.delete_task" user task as can_delete_task %}
        <div class="flex items-center"
             {% if can_change_task %}
             data-controller="ajax"
             data-ajax-replace-value
             data-ajax-url-value="{% url 'tasks:toggle_complete' task.id %}{% endif %}">
          {% include "cards/_task_description.html" %}
        </div>
        <div>
          {% if can_change_task %}
          <button data-action="toggle#toggle"
                  class="border px-4 py-1 rounded hover:bg-gray-100 mr-2">
            <i class="fa fa-pen mr-2"></i>{% translate "Edit" %}
          </button>
          {% endif %}
          {% if can_delete_task %}
          <button data-controller="ajax"
                  data-ajax-url-value="{% url 'tasks:delete_task' task.id %}"
                  data-action="ajax#post"
                  class="border border-red-800 px-4 py-1 rounded hover:bg-red-100 text-red-800">
            <i class="fa fa-trash mr-2"></i>{% translate "Delete" %}
          </button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% endfor %}
</div>

{% has_perm "tasks.create_task" user card as can_create_task %}
{% if can_create_task %}
<div data-controller="toggle"
     class="mb-3">
  <div data-toggle-target="item">
    <button data-action="toggle#toggle"
            class="border px-4 py-1 rounded hover:bg-gray-100 mr-2">
      <i class="fa fa-plus mr-2"></i>{% translate "Add New Task" %}
    </button>
  </div>
  <div class="hidden"
       data-toggle-target="item">
    <form class="sm:flex border p-2 items-center justify-between"
          data-controller="form"
          data-action="form#submit"
          method="post"
          action="{% url 'tasks:create_task' card.id %}">

      <div>
        <input type="text"
               required
               name="description"
               placeholder="Task description..."
               class="p-1 w-96">
      </div>
      <div>
        <button type="button"
                data-action="form#reset toggle#toggle"
                class="text-blue-800 hover:text-blue-600 mr-2">
          {% translate "Cancel" %}
        </button>
        <button type="submit"
                class="px-4 py-1 rounded bg-blue-800 hover:bg-blue-100 text-white">
          {% translate "Save" %}
        </button>
      </div>
    </form>
  </div>
</div>
{% endif %}

<h2 class="text-lg font-semibold mb-3">{% translate "Attachments" %}</h2>

{% if not attachments %}
<p class="mb-3 italic">
  {% translate "This card does not have any attachments" %}
</p>
{% endif %}

{% if attachments %}
<table class="table-auto p-3 w-full border mb-3">
  <thead>
    <tr class="bg-gray-100 text-left">
      <th class="p-2">{% translate "Filename" %}</th>
      <th class="p-2">{% translate "Type" %}</th>
      <th class="p-2"></th>
    </tr>
  </thead>
  <tbody>
    {% for attachment in attachments %}
    <tr {% if not forloop.last %}
        class="border-b"
        {% endif %}>
      <td class="p-2">{{ attachment.basename }}</td>
      <td class="p-2">{{ attachment.media_type }}</td>
      <td class="p-2 text-right">
        <a download
           class="border px-4 py-2 rounded hover:bg-gray-100 mr-3"
           href="{{ attachment.file.url }}">
          <i class="fa fa-download mr-2"></i>{% translate "Download" %}
        </a>

        {% has_perm "attachments.delete_attachment" user attachment as can_delete_attachment %}
        {% if can_delete_attachment %}
        <button data-controller="ajax"
                data-ajax-url-value="{% url 'attachments:delete_attachment' attachment.id %}"
                data-ajax-confirm-value="{% translate 'Are you sure you want to delete this?' %}"
                data-action="ajax#post"
                class="border border-red-800 px-4 py-1 rounded hover:bg-red-100 text-red-800">
          <i class="fa fa-trash mr-2"></i>{% translate "Delete" %}
        </button>
        {% endif %}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}
{% has_perm "attachments.create_attachment" user card as can_create_attachment %}
{% if can_create_attachment %}
<div data-controller="toggle">
  <div data-toggle-target="item">
    <button data-action="toggle#toggle"
            class="border px-4 py-1 rounded hover:bg-gray-100 mr-2">
      <i class="fa fa-upload mr-2"></i>{% translate "Add New Attachment" %}
    </button>
  </div>
  <div class="hidden"
       data-toggle-target="item">
    <form class="sm:flex border p-2 items-center justify-between"
          data-controller="form"
          data-action="form#submit"
          method="post"
          enctype="multipart/form-data"
          action="{% url 'attachments:create_attachment' card.id %}">

      <div>
        <input type="file"
               required
               name="file"
               class="p-1 w-96">
      </div>
      <div>
        <button type="button"
                data-action="form#reset toggle#toggle"
                class="text-blue-800 hover:text-blue-600 mr-2">
          {% translate "Cancel" %}
        </button>
        <button type="submit"
                class="px-4 py-1 rounded bg-blue-800 hover:bg-blue-100 text-white">
          {% translate "Save" %}
        </button>
      </div>
    </form>
  </div>
</div>
{% endif %}


{% endblock content %}