kando/cards/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "cards"

urlpatterns = [
    path("<int:card_id>/", views.card_detail, name="card_detail"),
    path("<int:card_id>/~edit/", views.edit_card, name="edit_card"),
    path("<int:card_id>/~delete/", views.delete_card, name="delete_card"),
    path("<int:project_id>/~create/", views.create_card, name="create_card"),
    path("<int:column_id>/~move/", views.move_cards, name="move_cards"),
    path(
        "<int:project_id>/<int:column_id>/~create/",
        views.create_card,
        name="create_card_for_column",
    ),
]

kando/columns/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "columns"

urlpatterns = [
    path("<int:project_id>/~create/", views.create_column, name="create_column"),
    path("<int:project_id>/~move/", views.move_columns, name="move_columns"),
    path("<int:column_id>/", views.column_detail, name="column_detail"),
    path("<int:column_id>/~edit/", views.edit_column, name="edit_column"),
    path("<int:column_id>/~delete/", views.delete_column, name="delete_column"),
]

kando/projects/urls.py
# Django
from django.urls import path

# Local
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.projects_overview, name="projects_overview"),
    path("<int:project_id>/board/", views.project_board, name="project_board"),
    path("<int:project_id>/members/", views.project_members, name="project_members"),
    path(
        "<int:member_id>/~/change-role/",
        views.change_member_role,
        name="change_member_role",
    ),
    path("<int:member_id>/~/remove/", views.remove_member, name="remove_member",),
    path(
        "<int:project_id>/member/<slug:username>/",
        views.project_member_detail,
        name="member_detail",
    ),
    path("<int:project_id>/~edit/", views.edit_project, name="edit_project"),
    path("<int:project_id>/~delete/", views.delete_project, name="delete_project"),
    path(
        "<int:project_id>/~duplicate/",
        views.duplicate_project,
        name="duplicate_project",
    ),
    path("~create/", views.create_project, name="create_project"),
]

kando/columns/models.py
# Django
from django.db import models
from django.urls import reverse

# Third Party Libraries
from model_utils.models import TimeStampedModel

# Kando
from kando.projects.models import Project


class Column(TimeStampedModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    position = models.IntegerField(default=0)
    show_in_dashboard = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("columns:column_detail", args=[self.id])

    def save(self, *args, **kwargs):
        if not self.position:
            self.position = (
                self.project.column_set.aggregate(models.Max("position"))[
                    "position__max"
                ]
                or 0
            ) + 1
        return super().save(*args, **kwargs)

kando/columns/forms.py
# Django
from django import forms

# Local
from .models import Column


class ColumnForm(forms.ModelForm):
    class Meta:
        model = Column
        fields = ("name",)

kando/columns/views.py
# Django
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST

# Kando
from kando.common.dragdrop import sort_draggable_items
from kando.common.http import HttpResponseNoContent
from kando.projects.models import Project
from kando.users.utils import has_perm_or_403

# Local
from .forms import ColumnForm
from .models import Column


@login_required
def column_detail(request, column_id):
    column = get_object_or_404(
        Column.objects.select_related("project", "project__owner"), pk=column_id
    )
    has_perm_or_403(request.user, "columns.view_column", column)
    cards = column.card_set.order_by("position").select_related(
        "owner", "project", "project__owner"
    )
    is_deletable = cards.count() == 0 and column.project.column_set.count() > 1

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (column.project.name, None),
    ]

    return TemplateResponse(
        request,
        "columns/detail.html",
        {
            "column": column,
            "cards": cards,
            "is_deletable": is_deletable,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
def create_column(request, project_id):
    project = get_object_or_404(Project.objects.select_related("owner"), pk=project_id)
    has_perm_or_403(request.user, "columns.create_column", project)
    if request.method == "POST":
        form = ColumnForm(request.POST)
        if form.is_valid():
            column = form.save(commit=False)
            column.project = project
            column.save()
            messages.success(request, _("Column has been added"))
            return redirect(project)
    else:
        form = ColumnForm()

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (_("New Column"), None),
    ]

    return TemplateResponse(
        request,
        "columns/column_form.html",
        {"form": form, "project": project, "breadcrumbs": breadcrumbs},
    )


@login_required
def edit_column(request, column_id):
    column = get_object_or_404(
        Column.objects.select_related("project", "project__owner"), pk=column_id
    )
    has_perm_or_403(request.user, "columns.change_column", column)
    if request.method == "POST":
        form = ColumnForm(request.POST, instance=column)
        if form.is_valid():
            form.save()
            messages.success(request, _("Column has been updated"))
            return redirect(column)
    else:
        form = ColumnForm(instance=column)

    breadcrumbs = [
        (_("Projects"), reverse("projects:projects_overview")),
        (column.name, column.get_absolute_url()),
        (_("Edit Column"), None),
    ]

    return TemplateResponse(
        request,
        "columns/column_form.html",
        {
            "form": form,
            "project": column.project,
            "column": column,
            "breadcrumbs": breadcrumbs,
        },
    )


@login_required
@require_POST
def delete_column(request, column_id):
    column = get_object_or_404(
        Column.objects.select_related("project", "project__owner"), pk=column_id
    )
    has_perm_or_403(request.user, "columns.delete_column", column)
    if column.card_set.count() > 0:
        messages.error(request, _("You cannot delete a column containing cards"))
    elif column.project.column_set.count() == 1:
        messages.error(request, _("You must have at least one column per project"))
    else:
        column.delete()
        messages.info(request, _("Column has been deleted"))
    return redirect(column.project)


@login_required
def move_columns(request, project_id):
    project = get_object_or_404(Project.objects.select_related("owner"), pk=project_id)

    for position, column in sort_draggable_items(
        request, project.column_set.all(), ["position"]
    ):
        column.position = position

    return HttpResponseNoContent()

templates/columns/column_form.html
{% extends "base.html" %}
{% load i18n widget_tweaks %}

{% block content %}
{% include "_breadcrumbs.html" %}

<h1 class="text-xl font-bold mb-3">
  {% if column %}
  {% translate "Edit Column" %}
  {% else %}
  {% translate "New Column" %}
  {% endif %}
</h1>
<form class="p-3 bg-white border rounded w-full lg:w-2/3{% if form.errors %} border-red-800{% endif %}"
      data-controller="form"
      data-action="form#submit"
      method="post"
      action="{{ request.path }}"
      novalidate>
  {% csrf_token %}
  {% with WIDGET_ERROR_CLASS="border-red-800 text-red-800" %}
  <div class="mb-3">
    <label class="font-semibold">
      {{ form.name.label }}
      {% render_field form.name class="p-1 w-full lg:w-96 lg:ml-3" %}
    </label>
    {% include "_form_errors.html" with errors=form.name.errors %}
    {% include "_form_help_text.html" with help_text=form.name.help_text %}
  </div>
  {% endwith %}
  <div class="flex items-center justify-end">
    <a href="{{ project.get_absolute_url }}"
       class="text-blue-800 hover:text-blue-600 mr-4">{% translate "Cancel" %}</a>
    <button type="submit"
            class="px-4 py-2 rounded bg-blue-800 hover:bg-blue-600 text-white">
      {% if column %}
      {% translate "Save Column" %}
      {% else %}
      {% translate "Create Column" %}
      {% endif %}
    </button>
  </div>
</form>
{% endblock %}

templates/columns/detail.html
{% extends "base.html" %}
{% load i18n account rules %}

{% block content %}
{% include "_breadcrumbs.html" %}

{% has_perm "cards.create_card" user column.project as can_create_card %}
{% has_perm "columns.change_column" user column as can_change_column %}
{% has_perm "columns.delete_column" user column as can_delete_column %}

<div class="flex items-center mb-3">
  {% if can_create_card or can_change_column or can_delete_column %}
  <div class="relative"
       data-controller="toggle">
    <button class="px-2 py-1 rounded border hover:bg-gray focus:outline-none text-lg mr-3"
            title="Actions..."
            data-action="toggle#toggle">
      <i class="fa fa-bars"></i>
    </button>
    <div class="rounded absolute hidden border shadow-xl z-50 opacity-100 p-2 mt-1 w-64 bg-white left-0"
         data-toggle-target="item"
         data-action="click@window->toggle#close keydown@window->toggle#close">

      {% if can_create_card %}
      <a href="{% url 'cards:create_card_for_column' column.project.id column.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-plus mr-2"></i>{% translate "Add Card" %}
      </a>
      {% endif %}

      {% if can_change_column %}
      <a href="{% url 'columns:edit_column' column.id %}"
         class="block p-1 rounded hover:bg-gray-100 w-full mb-2">
        <i class="fa fa-pen mr-2"></i>{% translate "Edit Column" %}
      </a>
      {% endif %}

      {% if can_delete_column and is_deletable %}
      <button data-controller="ajax"
              data-ajax-confirm-value="{% translate 'Are you sure you want to delete this column?' %}"
              data-ajax-url-value="{% url 'columns:delete_column' column.id %}"
              data-action="toggle#toggle ajax#post"
              class="block p-1 rounded hover:bg-red-100 text-red-800 w-full text-left">
        <i class="fa fa-trash mr-2"></i>{% translate "Delete Column" %}
      </button>
      {% endif %}

    </div>
  </div>
  {% endif %}

  <h1 class="text-xl font-bold">{{ column.name }}</h1>
</div>

{% if cards %}

<table class="table-auto p-3 w-full border mb-3">
  <thead>
    <tr class="bg-gray-100 text-left">
      <th class="p-2">{% translate "Card" %}</th>
      <th class="p-2">{% translate "Owner" %}</th>
      <th class="p-2">{% translate "Assignee" %}</th>
      <th class="p-2">{% translate "Priority" %}</th>
      <th class="p-2">{% translate "Complexity" %}</th>
      <th class="p-2">{% translate "Estimated Hours" %}</th>
    </tr>
  </thead>
  <tbody data-controller="drag"
         data-drag-group-value="shared"
         data-drag-url-value="{% url 'cards:move_cards' column.id %}">
    {% for card in cards %}
    {% has_perm "cards.move_card" user card as can_move_card %}
    <tr class="{% if can_move_card %} draggable{% endif %} hover:bg-gray-100"
        {% if can_move_card %}
        data-drag-target="draggable"
        data-group="shared"
        data-id="{{ card.id }}"
        {% endif %}>
      <td class="p-2">
        <a href="{{ card.get_absolute_url }}"
           class="text-blue-800 hover:text-blue-600">{{ card.name }}</a>
      </td>
      <td class="p-2">
        <a href="{% url 'projects:member_detail' card.project.id card.owner.username %}"
           class="text-blue-800 hover:text-blue-600">
          {% user_display card.owner %}
        </a>
      </td>
      <td class="p-2">
        {% if card.assignee %}
        <a href="{% url 'projects:member_detail' card.project.id card.assignee.username %}"
           class="text-blue-800 hover:text-blue-600">
          {% user_display card.assignee %}
        </a>
        {% else %}
        {% translate "Unassigned" %}
        {% endif %}
      </td>
      <td class="p-2">{{ card.priority }}</td>
      <td class="p-2">{{ card.complexity }}</td>
      <td class="p-2">{{ card.hours_estimated }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

{% endblock content %}